### PR TITLE
Update Santiago profile website

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by bryant1410** [comment]
> Cool, maybe a photo in your site?

A photo of what?

**Comment by matir91** [comment]
> A photo of what?

Of you! haha

**Comment by bryant1410** [comment]
It's there!

image

I think you're talking about the mobile version. Yeah, I should. One day.

**Comment by matir91** [comment]
Oh yes, that was the issue! My bad :smile:

**Pull request merged**
